
  name: buildOnly

  on:
    push:
      branches:
        - develop
        - feature/*
    pull_request:
      branches:
        - develop

  jobs:

    build:

      name: Gradle Build

      runs-on: ubuntu-latest

      steps:

        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup Java 21
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 21

        - name: Grant Execute Permission
          run: chmod +x gradlew

        - name: Build Application
          continue-on-error: true
          run: ./gradlew clean build

        - name: Build And Generate Coverage
          continue-on-error: true
          run:
            exit 1
            ./gradlew clean test jacocoTestReport


        - name: Upload JaCoCo Report
          uses: actions/upload-artifact@v4
          if : always()
          with:
           name: index.html
           path: service/build/reports/jacoco/test/html


